# Generated by Django 5.0.7 on 2025-07-12 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollingcenter',
            old_name='Constituency',
            new_name='constituency',
        ),
    ]
