# Generated by Django 5.0.7 on 2025-07-12 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_constituency_pollingcenter_constituency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollingcenter',
            old_name='name',
            new_name='region',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='party',
        ),
    ]
