# Generated by Django 5.0.7 on 2025-07-13 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_votesubmission_constituency_votesubmission_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votesubmission',
            name='constituency',
        ),
        migrations.RemoveField(
            model_name='votesubmission',
            name='region',
        ),
    ]
